language: node_js
env:
  - SESSION_SECRET=secret
services:
  - mongodb
cache:
  directories:
    - node_modules
branches:
  only:
    - develop
    - master
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run test
  - npm run lint
